version: "2"
services:
  web:
    restart: always
    build: ./Server/web
    ports:
     - "8000"
    command: /usr/local/bin/gunicorn -w 2 -b :8000 run
    volumes:
      - ./Data/data/vocab/:/app/data/vocab/

  nginx:
    restart: always
    build: ./Server/nginx
    ports:
      - "80:80"

  tfserver:
    restart: always
    build: ./Server/tfserver
    ports:
      - "9000:9000"
    volumes:
      - ./Model/output/model_serving/:/app/data/models/
